### ISSUE TITLE
Using papayaR with Rstudio on Linux

### ISSUE THREAD

**Issue by vascosa** [muschellij2/papayar#1]
Using papayaR on Rstudio it gives the error "Papaya requires Safari version 6 or higher." even though both Firefox and Chrome are installed and can use Papaya. My system default browser is Firefox. I am running neurodebian. Furthermore, it works from Terminal.

**Comment by muschellij2** [comment]
Can you see the result when you open in browser?  Using the button:

John

**Comment by NEONKID** [comment]
Hello.

I am a Ubuntu Linux 18.04 user. I also see the above error when I use the Papaya package,

User agent information was obtained from RStudio's internal viewer.

**5.0 (X11; N; Linux x86_64) AppleWebKit / 538.1 (KHTML, like Gecko) RStudio Safari / 538.1 Qt / 5.4.2**

It works well with the following changes made through the Inspector option.

**5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 68.0.3440.75 Safari / 537.36**

I checked using the navigator.appVersion method and checked the papaya.js file, but the code was so obsolete that it was difficult to fix it.

I hope this information helps.

**Comment by muschellij2** [comment]
I would maybe try papayaWidget: https://github.com/muschellij2/papayaWidget.
I will likely be changing papaya over to that code in the future.

Best,
John

John
