### ISSUE TITLE
Can't embed multiple papayas

### ISSUE THREAD

**Issue by avalcarcel9** [muschellij2/papayar#2]
I can't embed multiple papaya interactive widgets into a markdown document. It is possible to do but the `embed_papaya` function is not calling the correct files when an outdir is specified. When using the working directory the papaya.css and papaya.js files overwrite each other so its only possible to embed 1 widget. `embed_papaya` needs to be fixed to create the full filepaths as specified by outdir.

The papayarmultiple.pdf shows that it is possible to embed two papaya widgets but the second widget overwrite the first so two are presented but they are the same.
[papayarmultiple.pdf](https://github.com/muschellij2/papayar/files/3731222/papayarmultiple.pdf)

The papayarbug.pdf shows that trying to embed two widgets from distinct outdirs does not properly embed the images.
[papayarbug.pdf](https://github.com/muschellij2/papayar/files/3731234/papayarbug.pdf)

These are knit to pdf simply to attach to github here. Emailing you the .Rmd files so you can actually compile to html to see.

```r
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Mojave 10.14.5        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-10-15                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source                                
 abind         1.4-5   2016-07-21 [1] CRAN (R 3.6.0)                        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                        
 bitops        1.0-6   2013-08-17 [1] CRAN (R 3.6.0)                        
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)                        
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                        
 digest        0.6.21  2019-09-20 [1] CRAN (R 3.6.0)                        
 htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)                        
 httpuv        1.5.2   2019-09-11 [1] CRAN (R 3.6.0)                        
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.6.0)                        
 knitr         1.24    2019-08-08 [1] CRAN (R 3.6.0)                        
 later         1.0.0   2019-10-04 [1] CRAN (R 3.6.0)                        
 lubridate   * 1.7.4   2018-04-11 [1] CRAN (R 3.6.0)                        
 magrittr    * 1.5     2014-11-22 [1] CRAN (R 3.6.0)                        
 matrixStats   0.55.0  2019-09-07 [1] CRAN (R 3.6.0)                        
 neurobase     1.28.0  2019-10-15 [1] Github (muschellij2/neurobase@539a924)
 oro.nifti     0.10.1  2019-10-15 [1] Github (muschellij2/oro.nifti@28b3d33)
 papayar     * 1.0     2019-10-15 [1] Github (muschellij2/papayar@4222f8f)  
 promises      1.1.0   2019-10-04 [1] CRAN (R 3.6.0)                        
 R.methodsS3   1.7.1   2016-02-16 [1] CRAN (R 3.6.0)                        
 R.oo          1.22.0  2018-04-22 [1] CRAN (R 3.6.0)                        
 R.utils       2.9.0   2019-06-13 [1] CRAN (R 3.6.0)                        
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)                        
 Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.6.0)                        
 rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.0)                        
 RNifti        0.11.1  2019-08-01 [1] CRAN (R 3.6.0)                        
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.0)                        
 servr         0.15    2019-08-07 [1] CRAN (R 3.6.0)                        
 sessioninfo * 1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                        
 stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)                        
 stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)                        
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)                        
 xfun          0.10    2019-10-01 [1] CRAN (R 3.6.0)       

> papayar::get_papaya_version()
$version
character(0)

$build
[1] "1449"          
```

**Comment by muschellij2** [comment]
I'd try https://github.com/muschellij2/papayaWidget
Best,
John

**Comment by avalcarcel9** [comment]
`papayaWidget` seems to have similar problems. If you try to embed two distinct papaya widgets it will embed two of the second widget coded not the two distinct graphics. Same problem as found in papayarmultiple.pdf.

**Comment by muschellij2** [comment]
Try the Rmd here - worked for me:
[Untitled.Rmd.zip](https://github.com/muschellij2/papayar/files/3752814/Untitled.Rmd.zip)

**Comment by avalcarcel9** [comment]
For single image papaya widgets there are no issues it seems but overlaid graphics (i.e. `img = list(img1, img2)` the duplication problem persists. See the Rmd below.

[Untitled_amv.Rmd.zip](https://github.com/muschellij2/papayar/files/3752851/Untitled_amv.Rmd.zip)

**Comment by muschellij2** [comment]
Ahh weird.  So it works fine, but in a non-interactive setting it fails....
Best,
John

**Comment by muschellij2** [comment]
Confirm that
papaya(list(img1, img2))
Works interactively?

**Comment by muschellij2** [comment]
Fixed in papayaWidget: https://github.com/muschellij2/papayaWidget/commit/4febf63c6ee0033777692cf65cbf3a87d939fb5d

**Comment by avalcarcel9** [comment]
Thank you so much John! @simonvandekar this update to `papayaWidget` should fix issues you were having as well.

**Comment by simonvandekar** [comment]
KILLA! About to do a demo Thursday, so I'm excited to use it
